version: '3.8'

services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: myplates-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myplates-api
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    depends_on:
      - db

volumes:
  postgres-data:
  gradle-cache:
