version: '3.8'

services:
  db:
    image: postgres:15
    container_name: myplates-db
    env_file:
      - ./environment/db-variables.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myplates-api
    env_file:
      - ./environment/api-variables.env
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db

volumes:
  postgres-data:
