CREATE TABLE meal_record (
    id BIGSERIAL PRIMARY KEY,
    image_url TEXT NOT NULL,
    memo TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
